/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.wayang.api.jdbc;

import org.apache.wayang.basic.data.Record;

import java.sql.*;
import java.util.Collection;

/**
 * JDBC Statement implementation for Apache Wayang.
 *
 * This is the class that actually executes SQL queries by delegating to
 * SqlContext.executeSql() and wrapping results in a WayangResultSet.
 *
 * Flow: tool calls statement.executeQuery("SELECT ...") -> calls
 * sqlContext.executeSql(sql) -> gets back Collection<Record>
 * -> wraps in WayangResultSet -> returns to tool
 */
public class WayangStatement implements Statement {

    /**
     * The connection that created this statement
     */
    private final WayangConnection connection;

    /**
     * Whether this statement has been closed
     */
    private boolean closed = false;

    /**
     * The last ResultSet produced by this statement
     */
    private ResultSet currentResultSet = null;

    /**
     * Query timeout in seconds (0 = no limit)
     */
    private int queryTimeout = 0;

    /**
     * Max rows to return (0 = no limit)
     */
    private int maxRows = 0;

    public WayangStatement(final WayangConnection connection) {
        this.connection = connection;
    }

    /**
     * Executes a SQL SELECT query and returns results as a ResultSet. This is
     * the core method — it calls SqlContext.executeSql().
     *
     * @param sql The SQL query string e.g. "SELECT * FROM orders"
     * @return A WayangResultSet containing the query results
     */
    @Override
    public ResultSet executeQuery(final String sql) throws SQLException {
        checkClosed();
        try {
            // THIS IS THE KEY LINE — delegate to Wayang's SQL engine
            final Collection<Record> records = connection.getSqlContext().executeSql(sql);
            currentResultSet = new WayangResultSet(records, sql);
            return currentResultSet;
        } catch (Exception e) {
            throw new SQLException("Failed to execute query: " + sql + "\nReason: " + e.getMessage(), e);
        }
    }

    /**
     * Executes a SQL statement. For SELECT queries, use executeQuery instead.
     * Wayang is read-only so INSERT/UPDATE/DELETE are not supported.
     */
    @Override
    public boolean execute(final String sql) throws SQLException {
        checkClosed();
        final String trimmed = sql.trim().toUpperCase();
        if (trimmed.startsWith("SELECT")) {
            currentResultSet = executeQuery(sql);
            return true; // true means a ResultSet was produced
        }
        throw new SQLFeatureNotSupportedException(
                "Wayang only supports SELECT queries. Got: " + sql);
    }

    @Override
    public int executeUpdate(final String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("Wayang does not support INSERT/UPDATE/DELETE");
    }

    @Override
    public int executeUpdate(final String sql, final int autoGeneratedKeys) throws SQLException {
        throw new SQLFeatureNotSupportedException("Wayang does not support INSERT/UPDATE/DELETE");
    }

    @Override
    public int executeUpdate(final String sql, final int[] columnIndexes) throws SQLException {
        throw new SQLFeatureNotSupportedException("Wayang does not support INSERT/UPDATE/DELETE");
    }

    @Override
    public int executeUpdate(final String sql, final String[] columnNames) throws SQLException {
        throw new SQLFeatureNotSupportedException("Wayang does not support INSERT/UPDATE/DELETE");
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        return currentResultSet;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return -1; // -1 means no update count (we only do SELECT)
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return false; // Wayang only returns one result set
    }

    @Override
    public boolean getMoreResults(final int current) throws SQLException {
        return false;
    }

    @Override
    public Connection getConnection() throws SQLException {
        return connection;
    }

    @Override
    public void close() throws SQLException {
        closed = true;
        if (currentResultSet != null) {
            currentResultSet.close();
            currentResultSet = null;
        }
    }

    @Override
    public boolean isClosed() throws SQLException {
        return closed;
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        return queryTimeout;
    }

    @Override
    public void setQueryTimeout(final int seconds) throws SQLException {
        this.queryTimeout = seconds;
    }

    @Override
    public void setFetchSize(final int rows) throws SQLException {
        // no-op
    }

    @Override
    public int getMaxRows() throws SQLException {
        return maxRows;
    }

    @Override
    public void setMaxRows(final int max) throws SQLException {
        this.maxRows = max;
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        return 0;
    }

    @Override
    public void setMaxFieldSize(final int max) throws SQLException {
        // no-op
    }

    @Override
    public void setEscapeProcessing(final boolean enable) throws SQLException {
        // no-op
    }

    @Override
    public void cancel() throws SQLException {
        // no-op
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return null;
    }

    @Override
    public void clearWarnings() throws SQLException {
        // no-op
    }

    @Override
    public void setCursorName(final String name) throws SQLException {
        throw new SQLFeatureNotSupportedException("setCursorName not supported");
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        throw new SQLFeatureNotSupportedException("getGeneratedKeys not supported");
    }

    @Override
    public boolean execute(final String sql, final int autoGeneratedKeys) throws SQLException {
        return execute(sql);
    }

    @Override
    public boolean execute(final String sql, final int[] columnIndexes) throws SQLException {
        return execute(sql);
    }

    @Override
    public boolean execute(final String sql, final String[] columnNames) throws SQLException {
        return execute(sql);
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return ResultSet.CONCUR_READ_ONLY;
    }

    @Override
    public int getResultSetType() throws SQLException {
        return ResultSet.TYPE_FORWARD_ONLY;
    }

    @Override
    public void addBatch(final String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("Batch execution not supported");
    }

    @Override
    public void clearBatch() throws SQLException {
        throw new SQLFeatureNotSupportedException("Batch execution not supported");
    }

    @Override
    public int[] executeBatch() throws SQLException {
        throw new SQLFeatureNotSupportedException("Batch execution not supported");
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        return ResultSet.CLOSE_CURSORS_AT_COMMIT;
    }

    @Override
    public boolean isPoolable() throws SQLException {
        return false;
    }

    @Override
    public void setPoolable(final boolean poolable) throws SQLException {
        // no-op
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        // no-op
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return false;
    }

    @Override
    public int getFetchSize() throws SQLException {
        return 0;
    }

    @Override
    public void setFetchDirection(final int direction) throws SQLException {
        // no-op
    }

    @Override
    public int getFetchDirection() throws SQLException {
        return ResultSet.FETCH_FORWARD;
    }

    @Override
    public <T> T unwrap(final Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        throw new SQLException("Cannot unwrap to " + iface.getName());
    }

    @Override
    public boolean isWrapperFor(final Class<?> iface) throws SQLException {
        return iface.isInstance(this);
    }

    /**
     * Throws SQLException if this statement is already closed
     */
    private void checkClosed() throws SQLException {
        if (closed) {
            throw new SQLException("Statement is closed");
        }
    }
}
